### ISSUE TITLE
Mystical Powers failing to activate on clicking die in Mystical Power Sheet.

### ISSUE THREAD

**Issue by Veneratte** [pwatson100/symbaroum#462]
No apparent activation when clicking D20 on the mythical power sheet. Uncaught error in console when checked.  Reproducible across all powers tried with the same uncaught error.  

item.js:94 Uncaught (in promise) TypeError: ability.data.data?.script is not a function
[Detected 1 package: system:symbaroum]
    at MysticalPowerSheet._prepareActivateAbility (systems/symbaroum/script/sheet/item.js:94:54)
    at HTMLButtonElement.<anonymous> (systems/symbaroum/script/sheet/item.js:4:65)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)

Foundry Virtual Tabletop: Version 9, 9.255
Game System: symbaroum, 3.1.7
Active Modules: 9
Performance Mode: 1

**Comment by bithir** [comment]
Fixed in next release.
